USE [master]
GO
/****** Object:  Database [EZYD_20]    Script Date: 03/30/2013 22:50:42 ******/
CREATE DATABASE [EZYD_20] ON  PRIMARY 
( NAME = N'EZYD_20', FILENAME = N'D:\programs\Spawek Microsoft SQL Server\MSSQL10_50.SPAWEK_SQL\MSSQL\DATA\EZYD_20.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EZYD_20_log', FILENAME = N'D:\programs\Spawek Microsoft SQL Server\MSSQL10_50.SPAWEK_SQL\MSSQL\DATA\EZYD_20_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EZYD_20] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EZYD_20].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EZYD_20] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [EZYD_20] SET ANSI_NULLS OFF
GO
ALTER DATABASE [EZYD_20] SET ANSI_PADDING OFF
GO
ALTER DATABASE [EZYD_20] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [EZYD_20] SET ARITHABORT OFF
GO
ALTER DATABASE [EZYD_20] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [EZYD_20] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [EZYD_20] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [EZYD_20] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [EZYD_20] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [EZYD_20] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [EZYD_20] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [EZYD_20] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [EZYD_20] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [EZYD_20] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [EZYD_20] SET  DISABLE_BROKER
GO
ALTER DATABASE [EZYD_20] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [EZYD_20] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [EZYD_20] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [EZYD_20] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [EZYD_20] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [EZYD_20] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [EZYD_20] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [EZYD_20] SET  READ_WRITE
GO
ALTER DATABASE [EZYD_20] SET RECOVERY FULL
GO
ALTER DATABASE [EZYD_20] SET  MULTI_USER
GO
ALTER DATABASE [EZYD_20] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [EZYD_20] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'EZYD_20', N'ON'
GO
USE [EZYD_20]
GO
/****** Object:  Table [dbo].[TransactionsPending]    Script Date: 03/30/2013 22:50:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TransactionsPending](
	[transactionID] [int] NOT NULL,
	[plusGuyID] [bigint] NOT NULL,
	[minusGuyID] [bigint] NOT NULL,
	[value] [int] NOT NULL,
	[currency] [char](3) NOT NULL,
	[datetime] [datetime] NOT NULL,
	[description] [text] NULL,
 CONSTRAINT [PK_TransactionsPending] PRIMARY KEY CLUSTERED 
(
	[transactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_minusGuyID] ON [dbo].[TransactionsPending] 
(
	[minusGuyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_plusGuyID] ON [dbo].[TransactionsPending] 
(
	[plusGuyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_plusGuyID_plus_minusGuyID] ON [dbo].[TransactionsPending] 
(
	[plusGuyID] ASC,
	[minusGuyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TransactionsNew]    Script Date: 03/30/2013 22:50:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TransactionsNew](
	[transactionID] [int] NOT NULL,
	[userID] [bigint] NOT NULL,
	[ballance] [int] NOT NULL,
	[expense] [int] NULL,
	[income] [int] NULL,
	[currency] [char](3) NOT NULL,
	[datetime] [datetime] NOT NULL,
	[accepted] [bit] NOT NULL,
	[description] [text] NULL,
	[state] [tinyint] NOT NULL,
 CONSTRAINT [PK_TransactionsNew] PRIMARY KEY CLUSTERED 
(
	[transactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_transactionID] ON [dbo].[TransactionsNew] 
(
	[transactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_userID_plus_state] ON [dbo].[TransactionsNew] 
(
	[userID] ASC,
	[state] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'possible states = {awaiting = 1, cancelled = 2, history = 3}' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TransactionsNew', @level2type=N'COLUMN',@level2name=N'state'
GO
/****** Object:  Table [dbo].[QueriesLog]    Script Date: 03/30/2013 22:50:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QueriesLog](
	[ID] [int] NOT NULL,
	[query] [text] NULL,
	[datetime] [datetime] NULL,
	[error] [text] NULL,
 CONSTRAINT [PK_QueriesLog] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Friends]    Script Date: 03/30/2013 22:50:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Friends](
	[senderID] [bigint] NOT NULL,
	[receiverID] [bigint] NOT NULL,
	[accepted] [bit] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_receiverID] ON [dbo].[Friends] 
(
	[receiverID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_senderID] ON [dbo].[Friends] 
(
	[senderID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_senderID_plus_receiverID] ON [dbo].[Friends] 
(
	[senderID] ASC,
	[receiverID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Exceptions]    Script Date: 03/30/2013 22:50:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Exceptions](
	[ID] [int] NOT NULL,
	[message] [text] NULL,
	[stacktrace] [text] NULL,
	[datetime] [datetime] NULL,
 CONSTRAINT [PK_Exceptions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
