<?xml version="1.0" encoding="utf-8"?><Database Name="EZYD_20" Class="DbClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SPAWEKOLDLAP\SPAWEK_SQL;Initial Catalog=EZYD_20;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Friends" Member="Friends">
    <Type Name="Friend">
      <Column Name="senderID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="receiverID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="accepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QueriesLog" Member="QueriesLogs">
    <Type Name="QueriesLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="query" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="error" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionsNew" Member="TransactionsNews">
    <Type Name="TransactionsNew">
      <Column Name="transactionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ballance" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="expense" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="income" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="currency" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="accepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionsPending" Member="TransactionsPendings">
    <Type Name="TransactionsPending">
      <Column Name="transactionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="plusGuyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="minusGuyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="currency" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ExceptionsLog" Member="ExceptionsLogs">
    <Type Name="ExceptionsLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="stacktrace" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>